=begin
#virusapi

#The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

module CloudmersiveVirusScanApiClient
  VERSION = '2.2.1'
end
